clone:
  depth: full
pipelines:
  default:
    - step:
        script:
         - echo "Nothing occurred using the default pipeline."
  branches:
    master:
      - step:
          name: "Pushing changes to master at git@github.com:istuttered/reddit-auto-background.git"
          script:
            - git remote add reddit git@github.com:istuttered/reddit-auto-background.git
            - git pull reddit test-branch
            - git branch temp-branch
            - echo "CURRENT FOLDER"
            - ls
            - echo "PARENT FOLDER"
            - ls ..
            - cp ./test-branch/* ./temp-branch/.
            - git rm bitbucket-pipelines.yml
            - git add .
            - echo "ALL staged files"
            - git diff --name-only
            - git commit -m "Push from BitBucket to GitHub"
            #- git rebase master temp-branch
            - git push reddit temp-branch:test-branch
