clone:
  depth: full
pipelines:
  default:
    - step:
        script:
         - echo "Nothing occurred using the default pipeline."
  branches:
    master:
      - step:
          name: "Pushing changes to master at git@github.com:istuttered/reddit-auto-background.git"
          script:
            - git push --mirror git@github.com:istuttered/reddit-auto-background.git
    nate-new-feature:
      - step:
          name: "Pushing changes to nate-new-feature branch at git@github.com:istuttered/reddit-auto-background.git"
          script:
            - git push --mirror git@github.com:istuttered/reddit-auto-background.git nate-new-feature:nate-new-feature
