clone:
  depth: full
pipelines:
  default:
    - step:
        script:
         - echo "Nothing occurred using the default pipeline."
  branches:
    master:
      - step:
          name: "Pushing changes to master at git@github.com:istuttered/reddit-auto-background.git"
          script:
            - git remote add reddit git@github.com:istuttered/reddit-auto-background.git
            - echo "CURRENT BRANCH temp-branch"
            - git checkout --orphan temp-branch
            - git pull reddit test-branch
            - git merge master temp-branch
            - echo "ALL BRANCHES"
            - git branch --list
            - echo "CURRENT BRANCH test-branch"
            - git rm bitbucket-pipelines.yml --force --ignore-unmatch
            - git add .
            - ls
            - echo "ALL staged files"
            - git diff --name-only --staged
            - git commit -m "Push from BitBucket to GitHub"
            #- git rebase master temp-branch
            - git push reddit temp-branch:test-branch
