clone:
  depth: full
pipelines:
  default:
    - step:
        script:
         - echo "Nothing occurred using the default pipeline."
  branches:
    master:
      - step:
          name: "Pushing changes to master at git@github.com:iStuttered/reddit-auto-background.git"
          script:
            - git remote add reddit git@github.com:istuttered/reddit-auto-background.git
            - echo "CURRENT BRANCH temp-branch"
            - git checkout master
            - git rm bitbucket-pipelines.yml --force --ignore-unmatch
            - git commit -m "Removing pipeline file."
            - git fetch reddit test-branch:temp-branch-initial
            - git checkout temp-branch-initial
            - ls
            - git merge master temp-branch-initial -Xours
            - git checkout --orphan temp-branch-final temp-branch-initial
            #- git rebase master temp-branch
            - git push reddit temp-branch-initial:test-branch
